version: "3.0"
services:
  db:
    container_name: 'db'
    image: postgres:14
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_JOB_TRAINING_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_JOB_TRAINING_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_JOB_TRAINING_DB}"
      TZ: Asia/Seoul
